# Generated by Django 5.2.3 on 2025-09-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0006_location_alias'),
        ('candidatos', '0011_candidatohabilidadevaluada_and_more'),
        ('notifications', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimonthlyCommentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start date of the bimonthly period')),
                ('period_end', models.DateField(help_text='End date of the bimonthly period')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether the notification has been sent to the employer')),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True)),
                ('comment_provided', models.BooleanField(default=False, help_text='Whether the employer has provided a comment for this period')),
                ('comment_provided_at', models.DateTimeField(blank=True, help_text='When the comment was provided', null=True)),
                ('reminder_count', models.IntegerField(default=0, help_text='Number of reminders sent')),
                ('last_reminder_sent', models.DateTimeField(blank=True, help_text='When the last reminder was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(help_text='The candidate who needs evaluation', on_delete=django.db.models.deletion.CASCADE, to='candidatos.userprofile')),
                ('employer', models.ForeignKey(help_text='The employer who needs to provide comments', on_delete=django.db.models.deletion.CASCADE, to='agencia.employer')),
                ('job', models.ForeignKey(help_text='The job the candidate is currently assigned to', on_delete=django.db.models.deletion.CASCADE, to='agencia.job')),
            ],
            options={
                'verbose_name': 'Bimonthly Comment Reminder',
                'verbose_name_plural': 'Bimonthly Comment Reminders',
                'ordering': ['-period_start', 'employer', 'candidate'],
                'unique_together': {('employer', 'candidate', 'job', 'period_start')},
            },
        ),
    ]
