# Generated by Django 5.2.3 on 2025-09-18 03:07

from django.db import migrations
from django.core.management import call_command


def setup_periodic_tasks(apps, schema_editor):
    """Set up periodic tasks after migration"""
    try:
        call_command('setup_periodic_tasks')
    except Exception as e:
        # If there's an error, just log it and continue
        # This prevents migration failures in environments where celery isn't set up
        print(f"Warning: Could not set up periodic tasks: {e}")


def reverse_setup_periodic_tasks(apps, schema_editor):
    """No need to reverse periodic task setup"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_bimonthlycommentreminder'),
    ]

    operations = [
        migrations.RunPython(setup_periodic_tasks, reverse_setup_periodic_tasks),
    ]
