# Generated by Django 5.2.3 on 2025-08-20 00:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='All Day Event')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('personal', 'Personal'), ('private', 'Private'), ('confidential', 'Confidential')], default='normal', max_length=20, verbose_name='Sensitivity')),
                ('importance', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10, verbose_name='Importance')),
                ('reminder_is_set', models.BooleanField(default=False, verbose_name='Reminder Set')),
                ('reminder_minutes_before_start', models.IntegerField(blank=True, null=True, verbose_name='Reminder (Minutes Before)')),
                ('show_as', models.CharField(choices=[('free', 'Free'), ('tentative', 'Tentative'), ('busy', 'Busy'), ('oof', 'Out of Office'), ('workingelsewhere', 'Working Elsewhere')], default='busy', max_length=20, verbose_name='Show As')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Attendees')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='All Day Event')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('personal', 'Personal'), ('private', 'Private'), ('confidential', 'Confidential')], default='normal', max_length=20, verbose_name='Sensitivity')),
                ('importance', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10, verbose_name='Importance')),
                ('reminder_is_set', models.BooleanField(default=False, verbose_name='Reminder Set')),
                ('reminder_minutes_before_start', models.IntegerField(blank=True, null=True, verbose_name='Reminder (Minutes Before)')),
                ('show_as', models.CharField(choices=[('free', 'Free'), ('tentative', 'Tentative'), ('busy', 'Busy'), ('oof', 'Out of Office'), ('workingelsewhere', 'Working Elsewhere')], default='busy', max_length=20, verbose_name='Show As')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'historical Appointment',
                'verbose_name_plural': 'historical Appointments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
