# Generated by Django 5.1.2 on 2025-06-16 18:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCuestionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('inicio', models.BooleanField(default=False)),
                ('estado_desbloqueo', models.CharField(choices=[('Reg', 'Registro'), ('Pre', 'Preentrevista'), ('Can', 'Canalización'), ('Ent', 'Entrevista'), ('Cap', 'Capacitación'), ('Bol', 'Bolsa de Trabajo'), ('Emp', 'Empleado'), ('Des', 'Desempleado')], help_text='Estado necesario para desbloquear este cuestionario.', max_length=3)),
                ('responsable', models.CharField(choices=[('PCD', 'Persona con Discapacidad'), ('Psi', 'Psicólogo')], default='Psi', help_text='Dato necesario para determinar quién contesta este cuestionario.', max_length=3)),
            ],
            options={
                'verbose_name': 'Base Cuestionarios',
                'verbose_name_plural': 'Bases Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1, help_text='Número de versión del cuestionario.', validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=False, help_text='Indica si esta versión del cuestionario está activa.')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación de esta versión del cuestionario.')),
                ('base_cuestionario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='cuestionarios.basecuestionarios')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'unique_together': {('nombre', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=2500)),
                ('tipo', models.CharField(choices=[('multiple', 'Opción Múltiple'), ('abierta', 'Abierta'), ('numero', 'Número'), ('checkbox', 'Checkbox'), ('binaria', 'Binaria'), ('fecha', 'Fecha'), ('fecha_hora', 'Fecha y Hora'), ('dropdown', 'Dropdown'), ('sis', 'SIS DE 0-4'), ('sis2', 'SIS DE 0-2'), ('datos_personales', 'Datos Personales'), ('datos_domicilio', 'Datos Domicilio'), ('datos_medicos', 'Datos Médicos'), ('contactos', 'Contactos'), ('tipo_discapacidad', 'Discapacidad'), ('canalizacion', 'Canalización'), ('canalizacion_centro', 'Canalización Centro'), ('ed', 'Evaluación Diagnóstica'), ('ch', 'Cuadro de Habilidades'), ('imagen', 'Imagen')], default='multiple', max_length=50)),
                ('seccion_sis', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_seccion', models.CharField(default=' ', max_length=1000)),
                ('campo_ficha_tecnica', models.CharField(default=' ', max_length=2500)),
                ('campo_datos_personales', models.CharField(default=' ', max_length=2500)),
                ('actualiza_usuario', models.BooleanField(default=False, help_text='Si está marcado, la respuesta a esta pregunta actualizará la información del usuario.')),
                ('ficha_tecnica', models.BooleanField(default=False, help_text='Si está marcado, la respuesta a esta pregunta se verá en el api de ficha tecnica')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cuestionarios.cuestionario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('valor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cuestionarios.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='ImagenOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='preguntas_con_imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cuestionarios.pregunta')),
            ],
            options={
                'verbose_name': 'Imagen de pregunta',
                'verbose_name_plural': 'Imagenes de pregunta',
            },
        ),
        migrations.CreateModel(
            name='EstadoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inactivo', 'Inactivo'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='inactivo', max_length=20)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'cuestionario')},
            },
        ),
        migrations.CreateModel(
            name='DesbloqueoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionario')),
                ('opcion_desbloqueadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos', to='cuestionarios.opcion')),
                ('pregunta_desbloqueada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos_recibidos', to='cuestionarios.pregunta')),
                ('pregunta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos_hechos', to='cuestionarios.pregunta')),
            ],
            options={
                'unique_together': {('cuestionario', 'pregunta_origen', 'opcion_desbloqueadora', 'pregunta_desbloqueada')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.JSONField(blank=True, help_text='Almacena la respuesta en formato JSON.', null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('cuestionario', 'pregunta', 'usuario')},
            },
        ),
    ]
