# Generated by Django 5.2.3 on 2025-06-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('multiple', 'Opción Múltiple'), ('abierta', 'Abierta'), ('numero', 'Número'), ('checkbox', 'Checkbox'), ('binaria', 'Binaria'), ('fecha', 'Fecha'), ('fecha_hora', 'Fecha y Hora'), ('dropdown', 'Dropdown'), ('sis', 'SIS DE 0-4'), ('sis2', 'SIS DE 0-2'), ('datos_personales', 'Datos Personales'), ('datos_domicilio', 'Datos Domicilio'), ('datos_medicos', 'Datos Médicos'), ('contactos', 'Contactos'), ('tipo_discapacidad', 'Discapacidad'), ('canalizacion', 'Canalización'), ('canalizacion_centro', 'Canalización Centro'), ('ed', 'Evaluación Diagnóstica'), ('ch', 'Cuadro de Habilidades'), ('imagen', 'Imagen'), ('meta', 'Meta')], default='multiple', max_length=50),
        ),
    ]
