# Generated by Django 5.2.3 on 2025-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='profile_field_config',
            field=models.JSONField(blank=True, help_text='Configuration for profile field questions', null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='profile_field_path',
            field=models.CharField(blank=True, help_text="Path to the UserProfile field (e.g., 'personal_info.first_name')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('multiple', 'Opción Múltiple'), ('abierta', 'Abierta'), ('numero', 'Número'), ('checkbox', 'Checkbox'), ('binaria', 'Binaria'), ('fecha', 'Fecha'), ('fecha_hora', 'Fecha y Hora'), ('dropdown', 'Dropdown'), ('sis', 'SIS DE 0-4'), ('sis2', 'SIS DE 0-2'), ('datos_personales', 'Datos Personales'), ('datos_domicilio', 'Datos Domicilio'), ('datos_medicos', 'Datos Médicos'), ('contactos', 'Contactos'), ('tipo_discapacidad', 'Discapacidad'), ('canalizacion', 'Canalización'), ('canalizacion_centro', 'Canalización Centro'), ('ed', 'Evaluación Diagnóstica'), ('ch', 'Cuadro de Habilidades'), ('imagen', 'Imagen'), ('meta', 'Meta'), ('profile_field', 'Campo de Perfil'), ('profile_field_choice', 'Campo de Perfil - Selección'), ('profile_field_boolean', 'Campo de Perfil - Booleano'), ('profile_field_date', 'Campo de Perfil - Fecha'), ('profile_field_textarea', 'Campo de Perfil - Texto Largo')], default='multiple', max_length=50),
        ),
    ]
