# Generated by Django 5.2.3 on 2025-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0002_pregunta_profile_field_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('multiple', 'Opción Múltiple'), ('abierta', 'Abierta'), ('numero', 'Número'), ('checkbox', 'Checkbox'), ('binaria', 'Binaria'), ('fecha', 'Fecha'), ('fecha_hora', 'Fecha y Hora'), ('dropdown', 'Dropdown'), ('sis', 'SIS DE 0-4'), ('sis2', 'SIS DE 0-2'), ('datos_personales', 'Datos Personales'), ('datos_domicilio', 'Datos Domicilio'), ('datos_medicos', 'Datos Médicos'), ('contactos', 'Contactos'), ('tipo_discapacidad', 'Discapacidad'), ('medicamentos', 'Medicamentos'), ('canalizacion', 'Canalización'), ('canalizacion_centro', 'Canalización Centro'), ('ed', 'Evaluación Diagnóstica'), ('ch', 'Cuadro de Habilidades'), ('imagen', 'Imagen'), ('meta', 'Meta'), ('profile_field', 'Campo de Perfil'), ('profile_field_choice', 'Campo de Perfil - Selección'), ('profile_field_boolean', 'Campo de Perfil - Booleano'), ('profile_field_date', 'Campo de Perfil - Fecha'), ('profile_field_textarea', 'Campo de Perfil - Texto Largo'), ('profile_field_phonenumber', 'Campo de Perfil - Número de Teléfono')], default='multiple', max_length=50),
        ),
    ]
