# Generated by Django 5.2.3 on 2025-09-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0003_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='actualiza_usuario',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='campo_datos_personales',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='campo_ficha_tecnica',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='ficha_tecnica',
        ),
    ]
