# Generated by Django 5.1.2 on 2025-06-16 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoProyectoVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.JSONField(default=list, help_text='Lista de metas con su estado y pasos')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_proyecto_vida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Proyecto de Vida',
                'verbose_name_plural': 'Seguimientos de Proyectos de Vida',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoApoyos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('subitem', models.CharField(max_length=255)),
                ('ayuda_id', models.IntegerField()),
                ('ayuda_descripcion', models.TextField()),
                ('resultado', models.CharField(choices=[('funciono', 'Le funcionó'), ('no_funciono', 'No le funcionó'), ('no_especificado', 'No especificado')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_sesion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('sesion_seguimiento', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_apoyos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_sesion'],
                'indexes': [models.Index(fields=['usuario', 'sesion_seguimiento'], name='seguimiento_usuario_ea44b3_idx'), models.Index(fields=['fecha_sesion'], name='seguimiento_fecha_s_35b60d_idx')],
            },
        ),
    ]
