# Generated by Django 5.2.3 on 2025-08-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impediment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SISAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SISGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CHItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aid', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='discapacidad.chgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='discapacidad.disabilitygroup')),
            ],
        ),
        migrations.CreateModel(
            name='SISHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('sis_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudas', to='discapacidad.sisaid')),
            ],
        ),
        migrations.CreateModel(
            name='SISItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='discapacidad.sisgroup')),
            ],
        ),
        migrations.AddField(
            model_name='sisaid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sis_aids', to='discapacidad.sisitem'),
        ),
        migrations.CreateModel(
            name='TechnicalAidImpediment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('impediment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discapacidad.impediment')),
                ('technical_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discapacidad.technicalaid')),
            ],
            options={
                'unique_together': {('technical_aid', 'impediment')},
            },
        ),
        migrations.AddField(
            model_name='technicalaid',
            name='impediments',
            field=models.ManyToManyField(related_name='technical_aids', through='discapacidad.TechnicalAidImpediment', to='discapacidad.impediment'),
        ),
        migrations.CreateModel(
            name='TechnicalAidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=800)),
                ('technical_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='discapacidad.technicalaid')),
            ],
        ),
    ]
