# Generated by Django 5.2.3 on 2025-07-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalaidlink',
            name='url',
            field=models.URLField(max_length=800),
        ),
    ]
