# Generated by Django 5.2.3 on 2025-08-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='agency_state',
            field=models.CharField(choices=[('Bol', 'Bolsa de Trabajo'), ('Emp', 'Empleado'), ('Des', 'Desempleado')], default='Bol', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency_state',
            field=models.CharField(choices=[('Bol', 'Bolsa de Trabajo'), ('Emp', 'Empleado'), ('Des', 'Desempleado')], default='Bol', max_length=3),
        ),
    ]
