# Generated by Django 5.2.3 on 2025-08-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicile',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('ALBERGUE', 'Albergue'), ('INSTITUCION', 'Institución (asilo, centro de atención, etc.)'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='physical_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='physical_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
