# Generated by Django 5.2.3 on 2025-08-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_historicaluserprofile_agency_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaidcandidatehistory',
            options={'verbose_name': 'Aid History - Cuadro de Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='historicalsisaidcandidatehistory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Aid History - SIS', 'verbose_name_plural': 'historical Aid History - SISs'},
        ),
        migrations.AlterModelOptions(
            name='sisaidcandidatehistory',
            options={'verbose_name': 'Aid History - SIS'},
        ),
        migrations.AlterModelOptions(
            name='taidcandidatehistory',
            options={'verbose_name': 'Aid History - Technical(Evaluación Diagnóstica)'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='domicile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidatos.domicile'),
        ),
    ]
