# Generated by Django 5.2.3 on 2025-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_domicile_residence_type_emergencycontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='social_security',
            field=models.CharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('IMSS-BIENESTAR', 'IMSS-Bienestar'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro'), ('NINGUNO', 'Ninguno')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_security',
            field=models.CharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('IMSS-BIENESTAR', 'IMSS-Bienestar'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro'), ('NINGUNO', 'Ninguno')], max_length=20, null=True),
        ),
    ]
