# Generated by Django 5.2.3 on 2025-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_alter_chaidcandidatehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='lives_at_same_address',
            field=models.BooleanField(default=True),
        ),
    ]
