# Generated by Django 5.2.3 on 2025-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_alter_emergencycontact_lives_at_same_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
