# Generated by Django 5.2.3 on 2025-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_alter_historicaluserprofile_curp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicile',
            name='address_road',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
