# Generated by Django 5.2.3 on 2025-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_historicaluserprofile_nss_historicaluserprofile_rfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
