# Generated by Django 5.2.3 on 2025-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_alter_medication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('', 'No sé'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('', 'No sé'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3, null=True),
        ),
    ]
