# Generated by Django 5.2.3 on 2025-09-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0009_alter_historicaluserprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='social_security',
            field=models.CharField(blank=True, choices=[('NINGUNO', 'Ninguno'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('IMSS-BIENESTAR', 'IMSS-Bienestar'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_security',
            field=models.CharField(blank=True, choices=[('NINGUNO', 'Ninguno'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('IMSS-BIENESTAR', 'IMSS-Bienestar'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
