# Generated by Django 5.2.3 on 2025-09-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_habilidad_jobhabilidadrequerida_and_more'),
        ('candidatos', '0010_alter_historicaluserprofile_social_security_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoHabilidadEvaluada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_competencia', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='basico', max_length=20)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.userprofile')),
                ('evaluado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad Evaluada del Candidato',
                'verbose_name_plural': 'Habilidades Evaluadas de Candidatos',
                'ordering': ['-fecha_evaluacion'],
                'unique_together': {('candidato', 'habilidad')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='habilidades_evaluadas',
            field=models.ManyToManyField(blank=True, related_name='candidatos_con_habilidad', through='candidatos.CandidatoHabilidadEvaluada', to='agencia.habilidad'),
        ),
    ]
