# Generated by Django 5.1.12 on 2025-09-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0011_candidatohabilidadevaluada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='stage',
            field=models.CharField(choices=[('Reg', 'Registro'), ('Pre', 'Preentrevista'), ('Can', 'Canalización'), ('Ent', 'Entrevista'), ('Cap', 'Capacitación'), ('Agn', 'Agencia'), ('TrC', 'Trabajo en Casa')], default='Reg', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(choices=[('Reg', 'Registro'), ('Pre', 'Preentrevista'), ('Can', 'Canalización'), ('Ent', 'Entrevista'), ('Cap', 'Capacitación'), ('Agn', 'Agencia'), ('TrC', 'Trabajo en Casa')], default='Reg', max_length=3, null=True),
        ),
    ]
