# Generated by Django 5.2.3 on 2025-08-20 00:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentilesPorCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cuestionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='percentiles_cuestionario', to='cuestionarios.basecuestionarios')),
            ],
            options={
                'verbose_name': 'Percentiles por Cuestionario',
                'verbose_name_plural': 'Percentiles por Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='CalculoDeIndiceDeNecesidadesDeApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suma_estandar', models.IntegerField(help_text='Valor numérico de la suma de puntuaciones estándar')),
                ('percentil', models.CharField(help_text="Ejemplo: '5-10', '<1', '>99'", max_length=10)),
                ('indice_de_necesidades_de_apoyo', models.IntegerField(help_text='Valor numérico que representa el índice de necesidades de apoyo')),
                ('percentiles_por_cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indice_necesidades_apoyo', to='tablas_de_equivalencia.percentilesporcuestionario')),
            ],
            options={
                'verbose_name': 'Cálculo de Índice de Necesidades de Apoyo',
                'verbose_name_plural': 'Cálculos de Índice de Necesidades de Apoyo',
            },
        ),
        migrations.CreateModel(
            name='SeccionDePercentilesPorGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=255, unique=True)),
                ('grupo', models.CharField(default='todos', max_length=50)),
                ('percentiles_cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_percentiles', to='tablas_de_equivalencia.percentilesporcuestionario')),
            ],
            options={
                'verbose_name': 'Sección de Percentiles por Grupo',
                'verbose_name_plural': 'Secciones de Percentiles por Grupo',
            },
        ),
        migrations.CreateModel(
            name='RelacionDePuntuacionesYPercentiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_directa', models.CharField(help_text="Ejemplo: '<1', '1-5', '6-10'", max_length=10)),
                ('puntuacion_estandar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percentil', models.CharField(help_text="Ejemplo: '<1', '5-10', '>99'", max_length=10)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='tablas_de_equivalencia.secciondepercentilesporgrupo')),
            ],
            options={
                'verbose_name': 'Relación de Puntuaciones y Percentiles',
                'verbose_name_plural': 'Relaciones de Puntuaciones y Percentiles',
            },
        ),
    ]
