# table_templates.py

TABLE_TEMPLATES = {
    "Consideraciones": [
        ["Elemento", "¿Tiene?", "¿Pasa?", "Observaciones"],
        ["Certificado de discapacidad", None, None, None],
        ["Juicio de interdicción", None, None, None],
        ["Pensión de gobierno", None, None, None],
    ],
    "Evaluación Diagnóstica": [
        ["Habilidad", "Diagnóstico"],
        ["Lectura", None],
        ["Escritura", None],
        ["Números", None],
        ["Suma", None],
        ["Resta", None],
        ["Manejo de Dinero", None],
        ["Cruzar la Calle", None],
        ["Transporte", None],
        ["Comunicación", None]
    ],
    "Protección y Defensa": [
        ["Actividad", "Puntaje Directo"],
        ["Defenderse ante los demás", "9"],
        ["Manejar dinero y Finanzas personales", "10"],
        ["Protegerse a sí mismo de la explotación", "12"],
        ["Ejercer responsabilidades legales", "12"],
        ["Pertenecer a organizaciones de autoayuda", "10"],
        ["Obtener servicios legales", "9"],
        ["Hacer elecciones y tomar decisiones", "9"],
        ["Defender a otros", "11"]
    ],
    "Necesidades Médicas y Conductuales": [
        ["Pregunta", "Respuesta"],
        ["Introduzca la puntuación total de la sección 3a", "1"],
        ["¿Es la puntuación total mayor a 5?", "NO"],
        ["¿Hay al menos un '2' para necesidades médicas?", "SI"],
        ["Introduzca la puntuación total de la sección 3b", "1"],
        ["¿Es la puntuación mayor que 5?", "NO"],
        ["¿Hay al menos un '2' para necesidades conductuales?", "NO"]
    ],
    "Plan Personalizado de Apoyos": [
        ["Apoyo", "Nivel"],
        ["Necesidades de apoyo en casa", None],
        ["Necesidades de apoyo en la escuela", None],
        ["Necesidades de apoyo en el trabajo", None],
        ["Necesidades de apoyo en la comunidad", None],
        ["Estrategias recomendadas para el hogar", None],
        ["Estrategias recomendadas para la escuela", None],
        ["Estrategias recomendadas para el trabajo", None],
        ["Estrategias recomendadas para la comunidad", None],
        ["Recursos necesarios para el apoyo", None],
        ["Personas clave en mi plan", None],
        ["Plan de seguimiento y evaluación", None],
    ],
    "Habilidades Adaptativas - Tabla de resultados SIS": [
        ["PERCENTILES", "Vida en el hogar", "Vida en la comunidad", "Aprendizaje a lo largo de la vida", 
         "Empleo", "Salud y seguridad", "Social", "Índice de Necesidades de Apoyo", "PERCENTILES"],
        ["100", "17-20", "17-20", "17-20", "#N/A", "#N/A", "#N/A", ">137", "100"],
        ["95", "16", "15-16", "15-16", "15", "#N/A", "#N/A", "121-127", "95"],
        ["90", "15", "14", "14", "14", "14", "14", "117-120", "90"],
        ["85", "14", "", "-", "13", "13", "13", "114-116", "85"],
        ["80", "13", "13", "", "", "", "", "111-113", "80"],
        ["75", "", "", "", "12", "12", "12", "109-110", "75"],
        ["70", "12", "12", "", "", "", "", "107-108", "70"],
        ["65", "11", "11", "11", "11", "11", "11", "104-106", "65"],
        ["60", "", "", "", "", "", "", "102-103", "60"],
        ["55", "", "", "", "", "", "", "101", "55"],
        ["50", "10", "10", "10", "10", "10", "10", "98-100", "50"],
        ["45", "", "", "", "", "", "", "96-97", "45"],
        ["40", "9", "9", "9", "9", "9", "9", "93-95", "40"],
        ["35", "", "", "", "", "", "", "91-92", "35"],
        ["30", "8", "8", "8", "8", "8", "8", "89-90", "30"],
        ["25", "", "", "", "", "", "", "87-88", "25"],
        ["20", "7", "7", "7", "7", "7", "7", "84-86", "20"],
        ["15", "", "", "", "", "", "", "82-83", "15"],
        ["10", "6", "6", "6", "6", "6", "6", "79-81", "10"],
        ["5", "", "", "", "", "", "", "75-78", "5"],
        ["1", "1-5", "1-5", "1-4", "1-4", "1-4", "1-5", "<73", "1"]
    ],
}