# Generated by Django 5.2.3 on 2025-09-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('tecnica', 'Técnica'), ('blanda', 'Blanda'), ('fisica', 'Física'), ('cognitiva', 'Cognitiva'), ('social', 'Social')], default='blanda', max_length=50)),
                ('es_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='JobHabilidadRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_importancia', models.CharField(choices=[('esencial', 'Esencial'), ('importante', 'Importante'), ('deseable', 'Deseable')], default='importante', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.habilidad')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.job')),
            ],
            options={
                'verbose_name': 'Habilidad Requerida para Empleo',
                'verbose_name_plural': 'Habilidades Requeridas para Empleos',
                'unique_together': {('job', 'habilidad')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='habilidades_requeridas',
            field=models.ManyToManyField(blank=True, related_name='empleos_que_requieren', through='agencia.JobHabilidadRequerida', to='agencia.habilidad'),
        ),
    ]
