# Generated by Django 5.2.3 on 2025-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_habilidad_jobhabilidadrequerida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='horario',
            field=models.CharField(blank=True, help_text='Horario de trabajo (ej: Lunes a Viernes 8:00-17:00)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prestaciones',
            field=models.TextField(blank=True, help_text='Prestaciones ofrecidas (seguro médico, vales, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sueldo_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sueldo base mensual', max_digits=10, null=True),
        ),
    ]
