# Generated by Django 5.2.3 on 2025-09-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0004_job_horario_job_prestaciones_job_sueldo_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
