# Generated by Django 5.2.3 on 2025-09-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
