# Generated by Django 5.2.3 on 2025-09-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0006_location_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
