# Generated by Django 5.2.3 on 2025-09-11 16:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0007_alter_job_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalJob',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, help_text='Horario de trabajo (ej: Lunes a Viernes 8:00-17:00)', max_length=255, null=True)),
                ('sueldo_base', models.DecimalField(blank=True, decimal_places=2, help_text='Sueldo base mensual', max_digits=10, null=True)),
                ('prestaciones', models.TextField(blank=True, help_text='Prestaciones ofrecidas (seguro médico, vales, etc.)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agencia.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agencia.location')),
            ],
            options={
                'verbose_name': 'historical job',
                'verbose_name_plural': 'historical jobs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
