name: Build and deploy Python app to Azure Web App - confe-lin-webapp

on:
  push:
    branches:
      - stg
    paths:
      - 'backend/**'
      - '.github/workflows/stg_confe-lin-webapp.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd backend
          python manage.py collectstatic --noinput

      # The `zip` and `unzip` steps are no longer necessary in this combined job
      # as the `azure/webapps-deploy` action can deploy directly from a folder.

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'confe-lin-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FCFC18F720B4177B65FCAD2F702E3FA }}
          package: backend/ # Point to the directory with your built app
